### ISSUE TITLE
Visulization of the Part features

### ISSUE THREAD

**Issue by EddieAy** [robertdvdk/part_detection#2]
Thank you for your impressive work on Part Detection.

I wonder how can I reproduce the visulization results of the features like this   (I am sorry that I found github dosen't allow me to upload images.   It just looks like the Figure 5 in your paper    Figure 5. Discovered part segmentation with K = 4 on CUB)

By the way, can I use PDisconet with my own datasets ?(It is the same like Imagenet, but it dosen't have any part_annotations to evaluate. It only have  image label for per image  )

**Comment by robertdvdk** [comment]
You can reproduce the images from the paper using the show_maps function in lib.py! However the codebase is currently a bit of a mess, I'm working to clean it up!
